#!/usr/bin/env python3
# ==========================================================================
# build_site.py — Static HTML site generator (gitfolio-inspired)
# Generated by AI Agent: 2026-02-25 22:30 KST
# Rewritten by AI Agent: 2026-02-25 23:30 KST — 3그룹 계층 구조 + 라이트모드 전용
# Updated by AI Agent: 2026-02-26 07:55 KST — Dark/Light 토글 복원 + 그룹카드 통일
#
# 구조: Home(3 groups) → Group(sub-categories) → Category(posts) → Post
# ==========================================================================

from __future__ import annotations

import datetime as dt
import html as html_mod
import re
import shutil
from pathlib import Path

import markdown

REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_ROOT = REPO_ROOT / "blog_data"
TARGET_ROOT = REPO_ROOT / "blog"
INDEX_FILE = REPO_ROOT / "index.html"

HEADER_KEYS = {"Title", "URL", "PageID", "PostID", "Date", "Category"}
IMAGE_MARKER_RE = re.compile(r"^\[IMAGE:\s*images/([^\]]+)\]\s*$")
LIQUID_URL_RE = re.compile(r"\{\{\s*(https?://[^}\s]+)\s*\}\}")

MD = markdown.Markdown(extensions=["tables", "fenced_code", "nl2br"])

# ---------------------------------------------------------------------------
# 3-Group hierarchy mapping
# ---------------------------------------------------------------------------
GROUP_MAP: dict[str, dict] = {
    "AI": {
        "desc": "Agentic AI, Deep Learning, Machine Learning",
        "categories": [
            "Agentic_AI_Theory",
            "Deep-learning",
            "Machine_Learning",
            "Sensitivity_Analysis",
        ],
    },
    "BioMechanics": {
        "desc": "Blood Flow, Cardiovascular Diseases",
        "categories": [
            "Blood-Flow-and-Metabolism",
            "CardioVascular_Diseases",
        ],
    },
    "Mechanical_Engineering": {
        "desc": "Fluid Mechanics, Solid Mechanics, Thermodynamics, and more",
        "categories": [
            "Computational-Linear-Algebra",
            "Computational_Fluid_Dynamics",
            "Continuum-Mechanics",
            "Engineering_Mathematics",
            "Finite-Element-Method",
            "Fluid_Mechanics",
            "Gas_Dynamics",
            "Heat-transfer",
            "Solid_Mechanics",
            "Thermodynamics",
            "Viscous_Flow",
        ],
    },
}

GROUP_SLUGS = {
    "AI": "ai",
    "BioMechanics": "biomechanics",
    "Mechanical_Engineering": "mechanical-engineering",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(text: str) -> str:
    s = text.strip().lower()
    s = re.sub(r"[^a-z0-9가-힣]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "untitled"


def unique_slug(text: str, used: set[str]) -> str:
    base = slugify(text)
    slug = base
    idx = 2
    while slug in used:
        slug = f"{base}-{idx}"
        idx += 1
    used.add(slug)
    return slug


def parse_content(path: Path) -> tuple[dict[str, str], list[str]]:
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    meta: dict[str, str] = {}
    body_start = 0
    for i, line in enumerate(lines):
        if not line.strip() and meta:
            body_start = i + 1
            break
        m = re.match(r"^([A-Za-z][A-Za-z0-9]*):\s*(.*)$", line)
        if not m:
            break
        key, value = m.group(1), m.group(2)
        if key not in HEADER_KEYS:
            break
        meta[key] = value.strip()
        body_start = i + 1
    return meta, lines[body_start:]


def body_to_html(body_lines: list[str], title: str) -> str:
    preprocessed: list[str] = []
    for line in body_lines:
        img_m = IMAGE_MARKER_RE.match(line.strip())
        if img_m:
            preprocessed.append(f'![{title}](./images/{img_m.group(1).strip()})')
            continue
        normalized = LIQUID_URL_RE.sub(r"<\1>", line)
        normalized = normalized.replace("{{", "&#123;&#123;").replace("}}", "&#125;&#125;")
        preprocessed.append(normalized)
    MD.reset()
    return MD.convert("\n".join(preprocessed))


def format_date(raw: str) -> str:
    if not raw:
        return ""
    try:
        d = dt.datetime.fromisoformat(raw.replace("Z", "+00:00"))
        return d.strftime("%Y-%m-%d")
    except Exception:
        return raw[:10] if len(raw) >= 10 else raw


GITHUB_SVG = (
    '<svg viewBox="0 0 16 16" width="15" height="15" fill="currentColor">'
    '<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17'
    '.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94'
    '-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87'
    ' 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59'
    '.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27'
    '.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51'
    '.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07'
    '-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"'
    '/></svg>'
)


# ---------------------------------------------------------------------------
# Navigation builder
# ---------------------------------------------------------------------------

def build_nav(groups_data: list[dict], active_group: str = "", active_cat: str = "") -> str:
    items = []
    home_cls = "nav-item nav-home" + (" active" if not active_group else "")
    items.append(f'<a href="/" class="{home_cls}">Home</a>')
    for g in groups_data:
        items.append(f'<span class="nav-group-label">{html_mod.escape(g["name"])}</span>')
        for c in g["categories"]:
            cls = "nav-item"
            if c["slug"] == active_cat:
                cls += " active"
            items.append(
                f'<a href="/blog/{g["slug"]}/{c["slug"]}/" class="{cls}">'
                f'{html_mod.escape(c["name"])}'
                f'<span class="nav-post-count">{c["post_count"]}</span></a>'
            )
    return "\n        ".join(items)


# ---------------------------------------------------------------------------
# Page shell
# ---------------------------------------------------------------------------

def page_html(title: str, groups_data: list[dict], content: str,
              active_group: str = "", active_cat: str = "", root: str = "") -> str:
    safe_title = html_mod.escape(title)
    nav = build_nav(groups_data, active_group, active_cat)
    # === Updated by AI Agent: 2026-02-26 07:55 KST — 토글 버튼 + FOUC 방지 ===
    sun_svg = (
        '<svg class="icon-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
        ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
        '<circle cx="12" cy="12" r="5"/>'
        '<line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/>'
        '<line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/>'
        '<line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>'
        '<line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/>'
        '<line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/>'
        '<line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>'
    )
    moon_svg = (
        '<svg class="icon-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
        ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
        '<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>'
    )

    return f"""<!DOCTYPE html>
<html lang="ko" data-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{safe_title} | Sehyeog Kim</title>
  <link rel="stylesheet" href="{root}/assets/css/style.css">
  <script>!function(){{var t=localStorage.getItem("theme")||"light";document.documentElement.setAttribute("data-theme",t)}}();</script>
</head>
<body>
  <button class="theme-toggle" aria-label="Toggle theme">{sun_svg}{moon_svg}</button>

  <header class="mobile-header">
    <span class="site-title">Sehyeog Kim</span>
    <button class="menu-toggle" aria-label="Menu">&#9776;</button>
  </header>
  <div class="sidebar-overlay"></div>

  <div class="site-wrapper">
    <aside class="sidebar">
      <div class="sidebar-bg">
        <img src="{root}/assets/images/bg.jpg" alt="Background" onerror="this.style.display='none'">
      </div>
      <div class="sidebar-profile">
        <img class="profile-photo" src="{root}/assets/images/profile.jpg" alt="Sehyeog Kim"
             onerror="this.style.background='#eaeef2'">
        <h1 class="profile-name">Sehyeog Kim</h1>
        <p class="profile-bio">AI &amp; Computational Engineering<br>Personal Blog</p>
        <div class="profile-links">
          <a href="https://github.com/Sehyeogkim" target="_blank" rel="noopener">
            {GITHUB_SVG} GitHub
          </a>
        </div>
      </div>
      <nav class="sidebar-nav">
        {nav}
      </nav>
    </aside>

    <main class="main-content">
      {content}
      <footer class="site-footer">
        <p>&copy; {dt.datetime.now().year} Sehyeog Kim</p>
      </footer>
    </main>
  </div>
  <script src="{root}/assets/js/main.js"></script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Content builders
# ---------------------------------------------------------------------------

def build_home(groups_data: list[dict]) -> str:
    # === Updated by AI Agent: 2026-02-26 07:55 KST — 그룹카드를 category-card와 동일 스타일 사용 ===
    cards = []
    for g in groups_data:
        total = sum(c["post_count"] for c in g["categories"])
        cat_count = len(g["categories"])
        cards.append(
            f'<a class="category-card" href="/blog/{g["slug"]}/">'
            f'<h3>{html_mod.escape(g["name"])}</h3>'
            f'<div class="card-meta">'
            f'<span class="post-count-badge">{cat_count} categories &middot; {total} posts</span>'
            f'</div></a>'
        )
    return (
        '<div class="page-header">'
        '<h1>Personal Blog</h1>'
        '<p class="page-desc">'
        'Agentic AI\uc640 Numerical Analysis\uc758 \uc735\ud569\uc744 \ud0d0\uad6c\ud558\ub294 \ud559\uc2b5 \ub178\ud2b8\uc785\ub2c8\ub2e4.'
        '</p></div>\n'
        '<div class="category-grid">\n' + "\n".join(cards) + '\n</div>'
    )


def build_group(g: dict) -> str:
    cards = []
    for c in g["categories"]:
        if c["post_count"] == 0:
            continue
        cards.append(
            f'<a class="category-card" href="/blog/{g["slug"]}/{c["slug"]}/">'
            f'<h3>{html_mod.escape(c["name"])}</h3>'
            f'<div class="card-meta">'
            f'<span class="post-count-badge">{c["post_count"]} posts</span>'
            f'</div></a>'
        )
    return (
        '<div class="breadcrumb">'
        '<a href="/">Home</a><span class="sep">/</span>'
        f'<span>{html_mod.escape(g["name"])}</span></div>\n'
        f'<div class="page-header"><h1>{html_mod.escape(g["name"])}</h1>'
        f'<p class="page-desc">{html_mod.escape(g["desc"])}</p></div>\n'
        '<div class="category-grid">\n' + "\n".join(cards) + '\n</div>'
    )


def build_category(cat: dict, group: dict) -> str:
    lines = [
        '<div class="breadcrumb">',
        '<a href="/">Home</a><span class="sep">/</span>',
        f'<a href="/blog/{group["slug"]}/">{html_mod.escape(group["name"])}</a>'
        f'<span class="sep">/</span>',
        f'<span>{html_mod.escape(cat["name"])}</span></div>',
        f'<div class="page-header"><h1>{html_mod.escape(cat["name"])}</h1>',
        f'<p class="page-desc">{cat["post_count"]} posts</p></div>',
    ]
    if cat["posts"]:
        lines.append('<ul class="post-list">')
        for p in cat["posts"]:
            date_str = format_date(p.get("date", ""))
            date_html = f'<div class="post-date">{date_str}</div>' if date_str else ""
            lines.append(
                f'<li class="post-item"><a href="{p["url"]}">'
                f'<div class="post-title">{html_mod.escape(p["title"])}</div>'
                f'{date_html}</a></li>'
            )
        lines.append('</ul>')
    else:
        lines.append('<p>No posts yet.</p>')
    return "\n".join(lines)


def build_post(meta: dict, body_html: str, cat: dict, group: dict) -> str:
    title = html_mod.escape(meta.get("Title", "Untitled"))
    date_str = format_date(meta.get("Date", ""))
    cat_disp = html_mod.escape(cat["name"])
    grp_disp = html_mod.escape(group["name"])

    meta_items = []
    if date_str:
        meta_items.append(f'<span class="meta-item"><span class="meta-label">Date:</span> {date_str}</span>')
    meta_items.append(f'<span class="meta-item"><span class="meta-label">Category:</span> {cat_disp}</span>')
    src_url = meta.get("URL", "")
    if src_url:
        meta_items.append(
            f'<span class="meta-item"><span class="meta-label">Source:</span> '
            f'<a href="{html_mod.escape(src_url)}" target="_blank" rel="noopener">link</a></span>'
        )

    return (
        '<div class="breadcrumb">'
        '<a href="/">Home</a><span class="sep">/</span>'
        f'<a href="/blog/{group["slug"]}/">{grp_disp}</a><span class="sep">/</span>'
        f'<a href="/blog/{group["slug"]}/{cat["slug"]}/">{cat_disp}</a><span class="sep">/</span>'
        f'<span>{title}</span></div>\n'
        f'<a href="/blog/{group["slug"]}/{cat["slug"]}/" class="back-link">&larr; Back to {cat_disp}</a>\n'
        f'<div class="page-header"><h1>{title}</h1></div>\n'
        f'<div class="post-meta">{"".join(meta_items)}</div>\n'
        f'<article class="post-content">{body_html}</article>'
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    if not SOURCE_ROOT.exists():
        print(f"ERROR: source root not found: {SOURCE_ROOT}")
        return 1

    if TARGET_ROOT.exists():
        shutil.rmtree(TARGET_ROOT)
    TARGET_ROOT.mkdir(parents=True, exist_ok=True)

    # Build reverse lookup: category_dir_name → group_name
    cat_to_group: dict[str, str] = {}
    for gname, ginfo in GROUP_MAP.items():
        for cname in ginfo["categories"]:
            cat_to_group[cname] = gname

    groups_data: list[dict] = []
    processed = 0
    failed: list[str] = []

    for gname in ["AI", "BioMechanics", "Mechanical_Engineering"]:
        gslug = GROUP_SLUGS[gname]
        ginfo = GROUP_MAP[gname]
        g_out = TARGET_ROOT / gslug
        g_out.mkdir(parents=True, exist_ok=True)

        cat_list: list[dict] = []

        for cat_dir_name in ginfo["categories"]:
            cat_src = SOURCE_ROOT / cat_dir_name
            if not cat_src.exists():
                print(f"WARNING: category dir not found: {cat_dir_name}")
                continue

            cat_slug = slugify(cat_dir_name)
            cat_out = g_out / cat_slug
            cat_out.mkdir(parents=True, exist_ok=True)

            post_items: list[dict] = []
            used_post_slugs: set[str] = set()

            for post_dir in sorted(p for p in cat_src.iterdir() if p.is_dir()):
                content_file = post_dir / "content.txt"
                if not content_file.exists():
                    failed.append(f"{cat_dir_name}/{post_dir.name} (missing content.txt)")
                    continue
                try:
                    meta, body_lines = parse_content(content_file)
                    post_title = meta.get("Title") or post_dir.name
                    post_slug = unique_slug(post_dir.name, used_post_slugs)
                    post_out = cat_out / post_slug
                    post_out.mkdir(parents=True, exist_ok=True)

                    body_html = body_to_html(body_lines, post_title)

                    post_items.append({
                        "title": post_title,
                        "slug": post_slug,
                        "url": f"/blog/{gslug}/{cat_slug}/{post_slug}/",
                        "date": meta.get("Date", ""),
                        "meta": meta,
                        "body_html": body_html,
                        "src_images": post_dir / "images",
                        "out_dir": post_out,
                    })
                    processed += 1
                except Exception as exc:
                    failed.append(f"{cat_dir_name}/{post_dir.name} ({exc})")

            post_items.sort(key=lambda x: (x["date"] or "", x["slug"]), reverse=True)

            cat_info = {
                "name": cat_dir_name,
                "slug": cat_slug,
                "post_count": len(post_items),
                "posts": post_items,
            }
            cat_list.append(cat_info)

        groups_data.append({
            "name": gname,
            "slug": gslug,
            "desc": ginfo["desc"],
            "categories": cat_list,
        })

    # --- Write pages ---

    # Home
    INDEX_FILE.write_text(
        page_html("Home", groups_data, build_home(groups_data), root=""),
        encoding="utf-8",
    )

    # Group pages + category pages + post pages
    for g in groups_data:
        # Group index
        (TARGET_ROOT / g["slug"] / "index.html").write_text(
            page_html(g["name"], groups_data, build_group(g),
                       active_group=g["slug"], root="../.."),
            encoding="utf-8",
        )

        for cat in g["categories"]:
            cat_dir = TARGET_ROOT / g["slug"] / cat["slug"]
            # Category index
            (cat_dir / "index.html").write_text(
                page_html(cat["name"], groups_data, build_category(cat, g),
                           active_group=g["slug"], active_cat=cat["slug"],
                           root="../../.."),
                encoding="utf-8",
            )

            for p in cat["posts"]:
                # Post page
                (p["out_dir"] / "index.html").write_text(
                    page_html(p["title"], groups_data,
                              build_post(p["meta"], p["body_html"], cat, g),
                              active_group=g["slug"], active_cat=cat["slug"],
                              root="../../../.."),
                    encoding="utf-8",
                )

                # Copy images
                src_img = p["src_images"]
                dst_img = p["out_dir"] / "images"
                if src_img.exists():
                    dst_img.mkdir(parents=True, exist_ok=True)
                    for f in sorted(src_img.iterdir()):
                        if f.is_file():
                            shutil.copy2(f, dst_img / f.name)

    # Summary
    total_cats = sum(len(g["categories"]) for g in groups_data)
    print(f"groups processed: {len(groups_data)}")
    print(f"categories processed: {total_cats}")
    print(f"posts processed: {processed}")
    print(f"posts failed: {len(failed)}")
    if failed:
        print("failed items:")
        for item in failed:
            print(f"  - {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
