#!/usr/bin/env python3
# ==========================================================================
# build_site.py — Static HTML site generator (gitfolio-inspired)
# Generated by AI Agent: 2026-02-25 22:30 KST
# Updated by AI Agent: 2026-02-25 23:10 KST — Dark/Light 토글 + 텍스트 변경
#
# 기존 Jekyll/Markdown 방식(v1)을 전면 교체.
# blog_data/ → 순수 HTML 정적 사이트 생성.
# ==========================================================================
#
# === 기존 코드 (v1: Jekyll Markdown 출력) — 주석처리 시작 ===
# (원본 build_site.py v1은 git history에 보존됨)
# - front_matter(), write_home(), write_knowledge_map(), write_navigation() 등
#   Jekyll용 .md 파일 생성 로직이었음.
# - 현재 버전(v2)은 .nojekyll + 순수 HTML 출력 방식으로 전환.
# === 기존 코드 (v1) — 주석처리 끝 ===

from __future__ import annotations

import datetime as dt
import html as html_mod
import re
import shutil
from pathlib import Path

import markdown

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_ROOT = REPO_ROOT / "blog_data"
TARGET_ROOT = REPO_ROOT / "blog"
ASSETS_DIR = REPO_ROOT / "assets"
INDEX_FILE = REPO_ROOT / "index.html"

HEADER_KEYS = {"Title", "URL", "PageID", "PostID", "Date", "Category"}
IMAGE_MARKER_RE = re.compile(r"^\[IMAGE:\s*images/([^\]]+)\]\s*$")
LIQUID_URL_RE = re.compile(r"\{\{\s*(https?://[^}\s]+)\s*\}\}")

MD = markdown.Markdown(extensions=["tables", "fenced_code", "nl2br"])

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(text: str) -> str:
    s = text.strip().lower()
    s = re.sub(r"[^a-z0-9가-힣]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "untitled"


def unique_slug(text: str, used: set[str]) -> str:
    base = slugify(text)
    slug = base
    idx = 2
    while slug in used:
        slug = f"{base}-{idx}"
        idx += 1
    used.add(slug)
    return slug


def parse_content(path: Path) -> tuple[dict[str, str], list[str]]:
    raw = path.read_text(encoding="utf-8")
    lines = raw.splitlines()
    meta: dict[str, str] = {}
    body_start = 0

    for i, line in enumerate(lines):
        if not line.strip() and meta:
            body_start = i + 1
            break
        m = re.match(r"^([A-Za-z][A-Za-z0-9]*):\s*(.*)$", line)
        if not m:
            break
        key, value = m.group(1), m.group(2)
        if key not in HEADER_KEYS:
            break
        meta[key] = value.strip()
        body_start = i + 1

    body_lines = lines[body_start:]
    return meta, body_lines


def body_to_html(body_lines: list[str], title: str) -> str:
    """content.txt 본문을 HTML로 변환."""
    preprocessed: list[str] = []
    for line in body_lines:
        stripped = line.strip()
        img_m = IMAGE_MARKER_RE.match(stripped)
        if img_m:
            fname = img_m.group(1).strip()
            preprocessed.append(f'![{title}](./images/{fname})')
            continue
        normalized = LIQUID_URL_RE.sub(r"<\1>", line)
        normalized = normalized.replace("{{", "&#123;&#123;").replace("}}", "&#125;&#125;")
        preprocessed.append(normalized)

    md_text = "\n".join(preprocessed)
    MD.reset()
    return MD.convert(md_text)


def format_date(raw: str) -> str:
    if not raw:
        return ""
    try:
        d = dt.datetime.fromisoformat(raw.replace("Z", "+00:00"))
        return d.strftime("%Y-%m-%d")
    except Exception:
        return raw[:10] if len(raw) >= 10 else raw


# ---------------------------------------------------------------------------
# HTML Templates
# ---------------------------------------------------------------------------

GITHUB_SVG = (
    '<svg viewBox="0 0 16 16" width="16" height="16" fill="currentColor">'
    '<path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17'
    '.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94'
    '-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87'
    ' 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59'
    '.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27'
    '.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51'
    '.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07'
    '-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"'
    '/></svg>'
)

# === Updated by AI Agent: 2026-02-25 23:10 KST — Sun/Moon SVG 아이콘 추가 ===
SUN_SVG = (
    '<svg class="icon-sun" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
    ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
    '<circle cx="12" cy="12" r="5"/>'
    '<line x1="12" y1="1" x2="12" y2="3"/>'
    '<line x1="12" y1="21" x2="12" y2="23"/>'
    '<line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/>'
    '<line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>'
    '<line x1="1" y1="12" x2="3" y2="12"/>'
    '<line x1="21" y1="12" x2="23" y2="12"/>'
    '<line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/>'
    '<line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>'
    '</svg>'
)

MOON_SVG = (
    '<svg class="icon-moon" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
    ' stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
    '<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>'
    '</svg>'
)


def nav_html(categories: list[dict], active_slug: str = "") -> str:
    items = []
    items.append(
        f'<a href="/" class="nav-item nav-home{" active" if active_slug == "__home__" else ""}">Home</a>'
    )
    items.append('<span class="nav-label">Categories</span>')
    for c in categories:
        cls = "nav-item"
        if c["slug"] == active_slug:
            cls += " active"
        items.append(
            f'<a href="/blog/{c["slug"]}/" class="{cls}">'
            f'{html_mod.escape(c["name"])}'
            f'<span class="nav-post-count">{c["post_count"]}</span></a>'
        )
    return "\n        ".join(items)


def page_html(
    title: str,
    categories: list[dict],
    content: str,
    active_slug: str = "",
    root: str = "",
) -> str:
    safe_title = html_mod.escape(title)
    nav = nav_html(categories, active_slug)

    # === Updated by AI Agent: 2026-02-25 23:10 KST — 테마토글 + bio 텍스트 변경 ===
    return f"""<!DOCTYPE html>
<html lang="ko" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{safe_title} | Sehyeog Kim</title>
  <link rel="stylesheet" href="{root}/assets/css/style.css">
  <script>
    (function(){{var t=localStorage.getItem('theme')||'dark';document.documentElement.setAttribute('data-theme',t)}})();
  </script>
</head>
<body>
  <!-- Theme toggle -->
  <button class="theme-toggle" aria-label="Toggle theme">
    {SUN_SVG}
    {MOON_SVG}
  </button>

  <!-- Mobile header -->
  <header class="mobile-header">
    <span class="site-title">Sehyeog Kim</span>
    <button class="menu-toggle" aria-label="Menu">&#9776;</button>
  </header>
  <div class="sidebar-overlay"></div>

  <div class="site-wrapper">
    <!-- Sidebar -->
    <aside class="sidebar">
      <div class="sidebar-bg">
        <img src="{root}/assets/images/bg.jpg" alt="Background"
             onerror="this.style.display='none'">
      </div>
      <div class="sidebar-profile">
        <img class="profile-photo"
             src="{root}/assets/images/profile.jpg"
             alt="Sehyeog Kim"
             onerror="this.style.background='#21262d'">
        <h1 class="profile-name">Sehyeog Kim</h1>
        <p class="profile-bio">AI &amp; Computational Engineering<br>Personal Blog</p>
        <div class="profile-links">
          <a href="https://github.com/Sehyeogkim" target="_blank" rel="noopener">
            {GITHUB_SVG} GitHub
          </a>
        </div>
      </div>
      <nav class="sidebar-nav">
        {nav}
      </nav>
    </aside>

    <!-- Main content -->
    <main class="main-content">
      {content}
      <footer class="site-footer">
        <p>&copy; {dt.datetime.now().year} Sehyeog Kim. Built with gitfolio-inspired theme.</p>
      </footer>
    </main>
  </div>

  <script src="{root}/assets/js/main.js"></script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Page Generators
# ---------------------------------------------------------------------------

def build_home_content(categories: list[dict]) -> str:
    cards = []
    for c in categories:
        if c["post_count"] == 0:
            continue
        cards.append(
            f'<a class="category-card" href="/blog/{c["slug"]}/">'
            f'<h3>{html_mod.escape(c["name"])}</h3>'
            f'<div class="card-meta">'
            f'<span class="post-count-badge">{c["post_count"]} posts</span>'
            f'</div></a>'
        )

    # === Updated by AI Agent: 2026-02-25 23:10 KST — 홈 타이틀/설명 변경 ===
    return (
        '<div class="page-header">'
        "<h1>Personal Blog</h1>"
        '<p class="page-desc">Agentic AI와 Numerical Analysis의 융합을 탐구하는 학습 노트입니다.</p>'
        "</div>\n"
        '<div class="category-grid">\n'
        + "\n".join(cards)
        + "\n</div>"
    )


def build_category_content(cat_name: str, posts: list[dict]) -> str:
    lines = [
        '<div class="breadcrumb">',
        '  <a href="/">Home</a><span class="sep">/</span>',
        f"  <span>{html_mod.escape(cat_name)}</span>",
        "</div>",
        '<div class="page-header">',
        f"  <h1>{html_mod.escape(cat_name)}</h1>",
        f'  <p class="page-desc">{len(posts)} posts</p>',
        "</div>",
    ]

    if posts:
        lines.append('<ul class="post-list">')
        for p in posts:
            date_str = format_date(p.get("date", ""))
            date_html = f'<div class="post-date">{date_str}</div>' if date_str else ""
            lines.append(
                f'<li class="post-item">'
                f'<a href="{p["url"]}">'
                f'<div class="post-title">{html_mod.escape(p["title"])}</div>'
                f"{date_html}"
                f"</a></li>"
            )
        lines.append("</ul>")
    else:
        lines.append("<p>No posts yet.</p>")

    return "\n".join(lines)


def build_post_content(
    meta: dict[str, str], body_html: str, cat_name: str, cat_slug: str
) -> str:
    title = html_mod.escape(meta.get("Title", "Untitled"))
    date_str = format_date(meta.get("Date", ""))
    category_disp = html_mod.escape(cat_name)

    meta_items = []
    if date_str:
        meta_items.append(
            f'<span class="meta-item"><span class="meta-label">Date:</span> {date_str}</span>'
        )
    meta_items.append(
        f'<span class="meta-item"><span class="meta-label">Category:</span> {category_disp}</span>'
    )

    source_url = meta.get("URL", "")
    if source_url:
        meta_items.append(
            f'<span class="meta-item"><span class="meta-label">Source:</span> '
            f'<a href="{html_mod.escape(source_url)}" target="_blank" rel="noopener">link</a></span>'
        )

    return (
        '<div class="breadcrumb">'
        '  <a href="/">Home</a><span class="sep">/</span>'
        f'  <a href="/blog/{cat_slug}/">{category_disp}</a><span class="sep">/</span>'
        f"  <span>{title}</span>"
        "</div>\n"
        f'<a href="/blog/{cat_slug}/" class="back-link">&larr; Back to {category_disp}</a>\n'
        f'<div class="page-header"><h1>{title}</h1></div>\n'
        f'<div class="post-meta">{"".join(meta_items)}</div>\n'
        f'<article class="post-content">{body_html}</article>'
    )


# ---------------------------------------------------------------------------
# Main build
# ---------------------------------------------------------------------------

def main() -> int:
    if not SOURCE_ROOT.exists():
        print(f"ERROR: source root not found: {SOURCE_ROOT}")
        return 1

    if TARGET_ROOT.exists():
        shutil.rmtree(TARGET_ROOT)
    TARGET_ROOT.mkdir(parents=True, exist_ok=True)

    categories: list[dict] = []
    all_category_posts: dict[str, list[dict]] = {}
    processed_posts = 0
    failed_posts: list[str] = []

    used_category_slugs: set[str] = set()

    # --- Pass 1: scan categories & posts ---
    for category_dir in sorted(p for p in SOURCE_ROOT.iterdir() if p.is_dir()):
        category_name = category_dir.name
        category_slug = unique_slug(category_name, used_category_slugs)
        out_cat = TARGET_ROOT / category_slug
        out_cat.mkdir(parents=True, exist_ok=True)

        post_items: list[dict] = []
        used_post_slugs: set[str] = set()

        for post_dir in sorted(p for p in category_dir.iterdir() if p.is_dir()):
            content_file = post_dir / "content.txt"
            if not content_file.exists():
                failed_posts.append(f"{category_name}/{post_dir.name} (missing content.txt)")
                continue

            try:
                meta, body_lines = parse_content(content_file)
                post_title = meta.get("Title") or post_dir.name
                post_slug = unique_slug(post_dir.name, used_post_slugs)
                post_out = out_cat / post_slug
                post_out.mkdir(parents=True, exist_ok=True)

                body_html = body_to_html(body_lines, post_title)

                post_items.append({
                    "title": post_title,
                    "slug": post_slug,
                    "url": f"/blog/{category_slug}/{post_slug}/",
                    "date": meta.get("Date", ""),
                    "meta": meta,
                    "body_html": body_html,
                    "src_images": post_dir / "images",
                    "dst_images": post_out / "images",
                    "out_dir": post_out,
                    "cat_name": category_name,
                    "cat_slug": category_slug,
                })
                processed_posts += 1
            except Exception as exc:
                failed_posts.append(f"{category_name}/{post_dir.name} ({exc})")

        post_items.sort(key=lambda x: (x["date"] or "", x["slug"]), reverse=True)

        cat_info = {
            "name": category_name,
            "slug": category_slug,
            "url": f"/blog/{category_slug}/",
            "post_count": len(post_items),
        }
        categories.append(cat_info)
        all_category_posts[category_slug] = post_items

    categories.sort(key=lambda c: c["name"].lower())

    # --- Pass 2: write HTML pages ---

    # Home page
    home_content = build_home_content(categories)
    home_html = page_html("Home", categories, home_content, active_slug="__home__", root="")
    INDEX_FILE.write_text(home_html, encoding="utf-8")

    # Category & post pages
    for cat in categories:
        slug = cat["slug"]
        posts = all_category_posts.get(slug, [])

        cat_content = build_category_content(cat["name"], posts)
        cat_html = page_html(
            cat["name"], categories, cat_content, active_slug=slug, root="../.."
        )
        (TARGET_ROOT / slug / "index.html").write_text(cat_html, encoding="utf-8")

        for p in posts:
            post_content = build_post_content(p["meta"], p["body_html"], p["cat_name"], p["cat_slug"])
            post_html = page_html(
                p["title"], categories, post_content, active_slug=slug, root="../../.."
            )
            (p["out_dir"] / "index.html").write_text(post_html, encoding="utf-8")

            # Copy images
            src_img = p["src_images"]
            dst_img = p["dst_images"]
            if src_img.exists():
                dst_img.mkdir(parents=True, exist_ok=True)
                for f in sorted(src_img.iterdir()):
                    if f.is_file():
                        shutil.copy2(f, dst_img / f.name)

    # --- Summary ---
    print(f"categories processed: {len(categories)}")
    print(f"posts processed: {processed_posts}")
    print(f"posts failed: {len(failed_posts)}")
    if failed_posts:
        print("failed items:")
        for item in failed_posts:
            print(f"  - {item}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
